sbs_camera:
  ros__parameters:
    video_device: "/dev/v4l/by-id/usb-3D_USB_Camera_3D_USB_Camera_01.00.00-video-index0"
    image_size: [1280, 480]
    time_per_frame: [1, 15]
    pixel_format: "YUYV"
    output_encoding: "bgr8"
